export type Clause = {
  number: string
  title: string
  plain: string
  document: string
  evidence: string
  auditorAsks: string
}

export type Standard = {
  code: string
  name: string
  description: string
  shortCode: 'iso9001' | 'iso14001' | 'iso45001'
  clauses: Clause[]
}

export const ISO_9001_CLAUSES: Clause[] = [
  {
    number: '4.1',
    title: 'Understanding the organisation and its context',
    plain: "What's going on around you that affects your quality goals — markets, regulations, suppliers, competitors.",
    document: 'Context analysis document or SWOT/PESTLE summary',
    evidence: 'Current copy of the context analysis, reviewed within the last year',
    auditorAsks: 'Show me how you identify external and internal issues that affect your quality system.',
  },
  {
    number: '4.2',
    title: 'Needs and expectations of interested parties',
    plain: 'Who cares about what you do — customers, regulators, employees, owners — and what they expect.',
    document: 'Interested parties register',
    evidence: 'Up-to-date register listing parties, their needs, and how you address them',
    auditorAsks: 'Who are your interested parties and what do they expect from your QMS?',
  },
  {
    number: '4.3',
    title: 'Determining the scope of the QMS',
    plain: "What products, services, and sites your management system covers, and what's excluded.",
    document: 'Scope statement (often part of the quality manual)',
    evidence: 'Approved scope document covering products, services, sites, and exclusions with justification',
    auditorAsks: "What's the scope of your QMS? Why did you exclude any clauses?",
  },
  {
    number: '4.4',
    title: 'QMS and its processes',
    plain: 'The core activities that turn inputs into outputs, plus how they fit together and who owns them.',
    document: 'Process map or process flow diagram',
    evidence: 'Current process map with inputs, outputs, owners, and interactions',
    auditorAsks: 'Walk me through your core processes and how they connect.',
  },
  {
    number: '5.2',
    title: 'Quality policy',
    plain: 'A short statement from leadership about what quality means here and how you commit to it.',
    document: 'Signed quality policy statement',
    evidence: 'Current signed copy, communicated to employees, available to interested parties',
    auditorAsks: "Where is your quality policy? Can a random employee tell me what's in it?",
  },
  {
    number: '6.1',
    title: 'Actions to address risks and opportunities',
    plain: "The things that could go wrong (and the opportunities you could miss), and what you'll do about them.",
    document: 'Risk register or risk assessment',
    evidence: 'Active risk register with assessments and mitigation actions',
    auditorAsks: 'How do you identify and address risks to your QMS?',
  },
  {
    number: '6.2',
    title: 'Quality objectives',
    plain: 'Specific measurable quality goals tied to your policy, with deadlines and owners.',
    document: 'Quality objectives plan',
    evidence: 'Measurable objectives with targets, deadlines, owners, and progress tracking',
    auditorAsks: 'What are your quality objectives this year? How are you tracking them?',
  },
  {
    number: '7.2',
    title: 'Competence',
    plain: 'Making sure people doing the work have the right skills, training, and qualifications.',
    document: 'Competency matrix or job descriptions with training requirements',
    evidence: 'Training records, qualifications, evaluation of effectiveness',
    auditorAsks: 'How do you make sure people are competent for their roles?',
  },
  {
    number: '7.3',
    title: 'Awareness',
    plain: 'Making sure everyone knows the quality policy, their role in it, and what happens if things go wrong.',
    document: 'Awareness training plan or induction materials',
    evidence: 'Training records showing employees know the policy, objectives, and their contribution',
    auditorAsks: 'Pick an employee — can they explain how their work affects quality?',
  },
  {
    number: '7.4',
    title: 'Communication',
    plain: 'Who talks to whom about quality, internally and externally — and how.',
    document: 'Communication plan or matrix',
    evidence: 'Records of internal/external communication on quality matters',
    auditorAsks: 'How do you communicate about quality with your team and customers?',
  },
  {
    number: '7.5',
    title: 'Documented information',
    plain: 'The procedures, records, and information you keep, and how you control them (versions, approvals, retention).',
    document: 'Document control procedure',
    evidence: 'Document register with versions, approvals, distribution, retention',
    auditorAsks: 'Show me your latest procedure — who approved it, when, and how do people find the current version?',
  },
  {
    number: '8.1',
    title: 'Operational planning and control',
    plain: 'Planning and executing the work that delivers your product or service.',
    document: 'Operational planning procedure',
    evidence: 'Production plans, work orders, capacity records',
    auditorAsks: 'How do you plan and control the work that delivers your product?',
  },
  {
    number: '8.2',
    title: 'Customer requirements',
    plain: 'Capturing what customers actually need before, during, and after the sale — including changes.',
    document: 'Customer requirements review procedure',
    evidence: 'Order reviews, contracts, change records, customer communication logs',
    auditorAsks: 'How do you make sure you fully understand what each customer is ordering before you accept it?',
  },
  {
    number: '8.4',
    title: 'Externally provided processes, products and services',
    plain: 'Choosing, evaluating, and managing the people who supply you (materials, services, parts).',
    document: 'Supplier qualification and evaluation procedure',
    evidence: 'Approved supplier list with evaluations, incoming inspection records',
    auditorAsks: 'How do you choose and monitor your suppliers? Show me your approved supplier list.',
  },
  {
    number: '8.5',
    title: 'Production and service provision',
    plain: 'How you actually make the product or deliver the service, including handling, identification, and protection.',
    document: 'Production and service provision procedures',
    evidence: 'Work instructions, traceability records, handling and storage records',
    auditorAsks: 'Walk me through how a product is made from material arrival to shipment.',
  },
  {
    number: '9.1',
    title: 'Monitoring, measurement, analysis and evaluation',
    plain: 'What you measure, how often, and how you know your quality system is working.',
    document: 'Monitoring and measurement plan',
    evidence: 'KPI data, customer satisfaction results, data analysis reports',
    auditorAsks: 'What do you measure to know your QMS is working? Show me the data.',
  },
  {
    number: '9.2',
    title: 'Internal audit',
    plain: 'Regularly checking your own management system to find issues before an external auditor does.',
    document: 'Internal audit programme and procedure',
    evidence: 'Audit schedule, audit reports, follow-up records',
    auditorAsks: 'Show me your internal audit programme and the last few audit reports.',
  },
  {
    number: '9.3',
    title: 'Management review',
    plain: 'A regular meeting where leadership reviews how the quality system is performing and decides what to change.',
    document: 'Management review procedure and agenda',
    evidence: 'Minutes of management reviews covering required inputs and outputs',
    auditorAsks: 'When was your last management review? Show me the minutes and the actions that came out.',
  },
  {
    number: '10.2',
    title: 'Nonconformity and corrective action',
    plain: 'Investigating problems, fixing root causes, and preventing recurrence (Corrective and Preventive Action).',
    document: 'Corrective action procedure',
    evidence: 'CAPA register with investigations, root cause analyses, and verifications of effectiveness',
    auditorAsks: 'Pick a recent nonconformity — show me how you investigated and verified the fix worked.',
  },
  {
    number: '10.3',
    title: 'Continual improvement',
    plain: 'Continuously looking for ways to get better — not just fixing problems.',
    document: 'Improvement plan or continual improvement procedure',
    evidence: 'Improvement initiatives log with results, lessons learned',
    auditorAsks: 'What have you improved in the last year? Show me the evidence.',
  },
]


export const ISO_14001_CLAUSES: Clause[] = [
  {
    number: '4.1',
    title: 'Understanding the organisation and its context',
    plain: 'The internal and external issues — environmental conditions, regulations, stakeholders — that affect how you manage your environmental impact.',
    document: 'Context analysis covering environmental issues (often SWOT/PESTLE)',
    evidence: 'Current context analysis including environmental conditions affected by or affecting the organisation',
    auditorAsks: 'What external and internal issues are relevant to your environmental management system?',
  },
  {
    number: '4.2',
    title: 'Needs and expectations of interested parties',
    plain: 'Who cares about your environmental performance — regulators, neighbours, customers, investors — and which of their expectations become compliance obligations.',
    document: 'Interested parties register with environmental needs and compliance obligations flagged',
    evidence: 'Register identifying parties, their environmental expectations, and which ones you treat as obligations',
    auditorAsks: 'Which stakeholder expectations have you adopted as compliance obligations?',
  },
  {
    number: '4.3',
    title: 'Scope of the EMS',
    plain: 'Which activities, products, services, and sites the environmental management system covers.',
    document: 'EMS scope statement',
    evidence: 'Documented scope considering activities, products, services, and the authority to control or influence them',
    auditorAsks: "What's in scope for your EMS, and why are any units or sites excluded?",
  },
  {
    number: '5.2',
    title: 'Environmental policy',
    plain: 'A leadership commitment to protect the environment, meet compliance obligations, and continually improve.',
    document: 'Signed environmental policy',
    evidence: 'Current signed policy including commitments to protection, compliance, and improvement; communicated internally',
    auditorAsks: 'Show me your environmental policy. How do employees know what it commits to?',
  },
  {
    number: '6.1.2',
    title: 'Environmental aspects',
    plain: 'The ways your activities interact with the environment — emissions, waste, energy, water — and which of them are significant.',
    document: 'Environmental aspects and impacts register',
    evidence: 'Register of aspects and impacts with significance criteria and ratings, covering normal and abnormal conditions',
    auditorAsks: 'How do you identify and rate your significant environmental aspects?',
  },
  {
    number: '6.1.3',
    title: 'Compliance obligations',
    plain: 'The environmental laws, permits, and voluntary commitments that apply to you, tracked and kept current.',
    document: 'Legal and compliance obligations register',
    evidence: 'Up-to-date register of applicable legislation, permits, and other obligations with review dates',
    auditorAsks: 'Which environmental laws apply to you, and how do you keep this list current?',
  },
  {
    number: '6.2',
    title: 'Environmental objectives',
    plain: 'Measurable environmental goals — reduce waste, cut energy, lower emissions — with owners and deadlines.',
    document: 'Environmental objectives and programmes',
    evidence: 'Objectives with targets, responsibilities, deadlines, and progress tracking',
    auditorAsks: 'What are your environmental objectives and how are you progressing against them?',
  },
  {
    number: '7.2',
    title: 'Competence',
    plain: 'People whose work can cause significant environmental impact have the skills and training for it.',
    document: 'Competence requirements and training records for environmentally critical roles',
    evidence: 'Training records and competence evaluations for roles affecting environmental performance',
    auditorAsks: 'How do you ensure people in environmentally critical roles are competent?',
  },
  {
    number: '8.1',
    title: 'Operational planning and control',
    plain: 'Controls on the processes that create your significant environmental impacts — including outsourced ones and a life-cycle view.',
    document: 'Operational control procedures for significant aspects',
    evidence: 'Procedures and records showing controls applied, including for contractors and procurement',
    auditorAsks: 'Show me how you control the operations linked to your significant aspects.',
  },
  {
    number: '8.2',
    title: 'Emergency preparedness and response',
    plain: 'Plans for environmental emergencies — spills, fires, releases — and tests that prove they work.',
    document: 'Emergency preparedness and response plan',
    evidence: 'Emergency plans, drill records, and post-drill reviews',
    auditorAsks: 'What environmental emergencies have you planned for? When was the last drill?',
  },
  {
    number: '9.1',
    title: 'Monitoring, measurement, analysis and evaluation',
    plain: 'Measuring environmental performance and evaluating compliance with your obligations, with calibrated equipment where relevant.',
    document: 'Monitoring plan and compliance evaluation procedure',
    evidence: 'Monitoring data, calibration records, and periodic compliance evaluation reports',
    auditorAsks: 'What do you monitor, and show me your latest compliance evaluation.',
  },
  {
    number: '9.2',
    title: 'Internal audit',
    plain: 'Regularly auditing your own EMS to find weaknesses before regulators or certifiers do.',
    document: 'Internal EMS audit programme',
    evidence: 'Audit schedule, reports, and follow-up of findings',
    auditorAsks: 'Show me your EMS audit programme and recent findings.',
  },
  {
    number: '9.3',
    title: 'Management review',
    plain: 'Leadership periodically reviews environmental performance, compliance status, and resources, and decides on changes.',
    document: 'Management review procedure and minutes',
    evidence: 'Minutes covering required inputs including compliance status and interested party concerns',
    auditorAsks: 'When did leadership last review the EMS? Show me the decisions taken.',
  },
  {
    number: '10.2',
    title: 'Nonconformity and corrective action',
    plain: 'Investigating environmental incidents and nonconformities, fixing root causes, and preventing recurrence.',
    document: 'Corrective action procedure',
    evidence: 'Nonconformity register with root cause analyses and verified corrective actions',
    auditorAsks: 'Pick a recent environmental nonconformity — walk me through how you handled it.',
  },
]

export const ISO_45001_CLAUSES: Clause[] = [
  {
    number: '4.1',
    title: 'Understanding the organisation and its context',
    plain: 'The internal and external issues that affect worker health and safety — workforce, contractors, regulations, work environment.',
    document: 'Context analysis covering OH&S issues',
    evidence: 'Current context analysis addressing conditions that affect occupational health and safety',
    auditorAsks: 'What issues internal and external to the business affect your OH&S system?',
  },
  {
    number: '4.2',
    title: 'Needs and expectations of workers and other interested parties',
    plain: 'What workers, regulators, unions, and contractors expect for health and safety, and which expectations you adopt as requirements.',
    document: 'Interested parties register with worker needs identified',
    evidence: 'Register including workers and their representatives, with legal and adopted requirements flagged',
    auditorAsks: 'How have you captured what your workers expect from the OH&S system?',
  },
  {
    number: '5.2',
    title: 'OH&S policy',
    plain: 'A leadership commitment to safe and healthy workplaces, eliminating hazards, and consulting workers.',
    document: 'Signed OH&S policy',
    evidence: 'Current signed policy with commitments to prevent injury and ill health, fulfil legal requirements, and ensure worker participation',
    auditorAsks: 'Show me your OH&S policy. Can workers on the floor tell me what it promises them?',
  },
  {
    number: '5.4',
    title: 'Consultation and participation of workers',
    plain: 'Workers at all levels genuinely involved in identifying hazards, setting controls, and shaping the safety system.',
    document: 'Worker consultation and participation procedure',
    evidence: 'Safety committee minutes, consultation records, mechanisms for non-managerial workers to participate',
    auditorAsks: 'How do non-managerial workers participate in hazard identification and decision-making?',
  },
  {
    number: '6.1.2',
    title: 'Hazard identification and assessment of risks',
    plain: 'Systematically finding what could hurt people — routine and non-routine work, human factors, past incidents — and rating the risks.',
    document: 'Hazard identification procedure and risk assessment register',
    evidence: 'Current risk assessments covering all activities, with methodology and ratings',
    auditorAsks: 'How do you identify hazards? Show me the risk assessment for this area.',
  },
  {
    number: '6.1.3',
    title: 'Legal and other requirements',
    plain: 'The health and safety laws and other requirements that apply to you, tracked and kept current.',
    document: 'OH&S legal register',
    evidence: 'Up-to-date register of applicable OH&S legislation and other requirements',
    auditorAsks: 'Which OH&S regulations apply to your operations, and how do you stay current?',
  },
  {
    number: '6.2',
    title: 'OH&S objectives',
    plain: 'Measurable safety goals — reduce incidents, improve reporting, complete training — with owners and deadlines.',
    document: 'OH&S objectives and plans',
    evidence: 'Objectives with targets, responsibilities, deadlines, and progress measurement',
    auditorAsks: 'What are your safety objectives this year and how are they tracking?',
  },
  {
    number: '7.2',
    title: 'Competence',
    plain: 'Workers have the skills and training to work safely, including for the specific hazards of their tasks.',
    document: 'Competence requirements, training matrix and records',
    evidence: 'Training records, licences, and competence evaluations for safety-critical work',
    auditorAsks: 'How do you verify a worker is competent before they do hazardous work?',
  },
  {
    number: '8.1.2',
    title: 'Eliminating hazards and reducing OH&S risks',
    plain: 'Applying the hierarchy of controls — eliminate first, PPE last — to reduce risks.',
    document: 'Risk control procedures referencing the hierarchy of controls',
    evidence: 'Risk assessments showing controls chosen per the hierarchy, not defaulting to PPE',
    auditorAsks: 'For this risk, why was this control chosen? What higher-order controls were considered?',
  },
  {
    number: '8.2',
    title: 'Emergency preparedness and response',
    plain: 'Plans for safety emergencies — fire, injury, chemical exposure — with training, drills, and first aid arrangements.',
    document: 'Emergency response plan',
    evidence: 'Emergency plans, evacuation drill records, first aid provisions and trained responders',
    auditorAsks: 'When was your last evacuation drill and what did you learn from it?',
  },
  {
    number: '9.1',
    title: 'Monitoring, measurement, analysis and performance evaluation',
    plain: 'Measuring safety performance — incidents, near misses, exposure monitoring, legal compliance — and acting on the data.',
    document: 'OH&S monitoring plan and compliance evaluation procedure',
    evidence: 'Incident statistics, health surveillance and workplace monitoring records, compliance evaluations',
    auditorAsks: 'What safety metrics do you track and show me your latest legal compliance evaluation.',
  },
  {
    number: '9.2',
    title: 'Internal audit',
    plain: 'Regularly auditing your own OH&S system to find weaknesses before they cause harm.',
    document: 'Internal OH&S audit programme',
    evidence: 'Audit schedule, reports, and follow-up records',
    auditorAsks: 'Show me your OH&S audit programme and how findings get closed.',
  },
  {
    number: '9.3',
    title: 'Management review',
    plain: 'Leadership periodically reviews safety performance, incidents, worker feedback, and resources, and decides on changes.',
    document: 'Management review procedure and minutes',
    evidence: 'Minutes covering incidents, consultation outcomes, compliance status, and resulting actions',
    auditorAsks: 'Show me the minutes of your last OH&S management review.',
  },
  {
    number: '10.2',
    title: 'Incident, nonconformity and corrective action',
    plain: 'Investigating incidents and near misses with worker participation, fixing root causes, and preventing recurrence.',
    document: 'Incident investigation and corrective action procedure',
    evidence: 'Incident register with investigations, root cause analyses, and verified corrective actions',
    auditorAsks: 'Pick a recent incident — show me the investigation and what changed because of it.',
  },
]

export const STANDARDS: Standard[] = [
  {
    code: 'ISO 9001:2015',
    name: 'Quality management',
    description: "The world's most widely adopted quality management standard. Applies to any organisation, of any size, in any industry.",
    shortCode: 'iso9001',
    clauses: ISO_9001_CLAUSES,
  },
  {
    code: 'ISO 14001:2015',
    name: 'Environmental management',
    description: 'Requirements for an environmental management system — how the organisation identifies and controls its environmental impacts.',
    shortCode: 'iso14001',
    clauses: ISO_14001_CLAUSES,
  },
  {
    code: 'ISO 45001:2018',
    name: 'Health and safety',
    description: 'Requirements for an occupational health and safety management system — preventing work-related injury and ill health.',
    shortCode: 'iso45001',
    clauses: ISO_45001_CLAUSES,
  },
]
